# Oracle Cloud Infrastructure (OCI) Credentials Secret Template
# IMPORTANT: Do not commit actual credentials to version control!
# NOTE: If namespace is not provided (in secret or task parameters), it will be auto-detected

apiVersion: v1
kind: Secret
metadata:
  name: oci-credentials
type: Opaque
stringData:
  # REQUIRED: OCI API Private Key (PEM format)
  oci_api_key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    YOUR_ACTUAL_PRIVATE_KEY_CONTENT_HERE
    -----END RSA PRIVATE KEY-----

  # REQUIRED: API Key Fingerprint
  fingerprint: "YOUR_API_KEY_FINGERPRINT_HERE"

  # OPTIONAL: These can be provided as task parameters instead
  tenancy_ocid: "ocid1.tenancy.oc1..example_tenancy_id"
  user_ocid: "ocid1.user.oc1..example_user_id"
  region: "us-ashburn-1"
  namespace: "your-namespace-here"  # Will be auto-detected if not provided
---
# Alternative: Create secret from files using kubectl
# kubectl create secret generic oci-credentials \
#   --from-file=oci_api_key.pem=~/.oci/oci_api_key.pem \
#   --from-literal=fingerprint="12:34:56:78:90:ab:cd:ef:12:34:56:78:90:ab:cd:ef" \
#   --from-literal=tenancy_ocid="ocid1.tenancy.oc1..example_tenancy_id" \
#   --from-literal=user_ocid="ocid1.user.oc1..example_user_id" \
#   --from-literal=region="us-ashburn-1" \
#   --from-literal=namespace="your-namespace"  # Optional - auto-detected if omitted
#
# Optional files (can be provided as task parameters instead):
#   - tenancy_ocid: Your OCI tenancy OCID
#   - user_ocid: Your OCI user OCID
#   - region: Your OCI region
#   - namespace: Your Object Storage namespace (auto-detected if not provided)
#
# When you create a secret and mount it as a workspace, Kubernetes automatically
# creates these files from the secret's stringData/data fields.
#
# Example TaskRun workspace configuration:
#   workspaces:
#   - name: credentials
#     secret:
#       secretName: oci-credentials
