# Simple TaskRun using the oracle-cloud-storage-upload task
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: oracle-cloud-storage-upload-simple
spec:
  taskRef:
    name: oracle-cloud-storage-upload
  params:
  - name: path
    value: "."
  - name: bucketName
    value: "my-bucket"
  - name: objectPrefix
    value: "uploads/demo"
  - name: tenancyOcid
    value: "ocid1.tenancy.oc1..example_tenancy_id"
  - name: userOcid
    value: "ocid1.user.oc1..example_user_id"
  - name: region
    value: "us-phoenix-1"
  # namespace parameter omitted - will be auto-detected using 'oci os ns get'
  - name: recursive
    value: "true"
  - name: replaceExistingFiles
    value: "true"
  - name: deleteExtraFiles
    value: "false"
  workspaces:
  - name: credentials
    secret:
      secretName: oci-credentials
  - name: source
    emptyDir: {}
---
# TaskRun using complete credentials secret
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: oracle-cloud-storage-upload-with-secret-config
spec:
  taskRef:
    name: oracle-cloud-storage-upload
  params:
  - name: path
    value: "."
  - name: bucketName
    value: "bucket-20251014-2017"
  - name: objectPrefix
    value: "uploads/minimal-config"
  # No OCI configuration parameters needed - all in secret!
  - name: recursive
    value: "true"
  - name: replaceExistingFiles
    value: "true"
  - name: deleteExtraFiles
    value: "false"
  workspaces:
  - name: credentials
    secret:
      secretName: oci-credentials
  - name: source
    emptyDir: {}
---
# Sync TaskRun using the oracle-cloud-storage-upload task with deleteExtraFiles
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: oracle-cloud-storage-sync
spec:
  taskRef:
    name: oracle-cloud-storage-upload
  params:
  - name: path
    value: "."
  - name: bucketName
    value: "my-bucket"
  - name: objectPrefix
    value: "sync-demo/release-artifacts"
  - name: tenancyOcid
    value: "ocid1.tenancy.oc1..example_tenancy_id"
  - name: userOcid
    value: "ocid1.user.oc1..example_user_id"
  - name: region
    value: "us-phoenix-1"
  - name: namespace
    value: "example-namespace"  # Optional: can be omitted for auto-detection
  - name: recursive
    value: "true"
  - name: replaceExistingFiles
    value: "true"
  - name: deleteExtraFiles
    value: "true"  # This will delete files in bucket not present in local directory
  workspaces:
  - name: credentials
    secret:
      secretName: oci-credentials
  - name: source
    emptyDir: {}
---
# Advanced TaskRun with extraArgs for metadata and performance tuning
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: oracle-cloud-storage-upload-with-extraargs
spec:
  taskRef:
    name: oracle-cloud-storage-upload
  params:
  - name: path
    value: "."
  - name: bucketName
    value: "my-bucket"
  - name: objectPrefix
    value: "releases/v2.0.0"
  - name: tenancyOcid
    value: "ocid1.tenancy.oc1..example_tenancy_id"
  - name: userOcid
    value: "ocid1.user.oc1..example_user_id"
  - name: region
    value: "us-phoenix-1"
  - name: recursive
    value: "true"
  - name: replaceExistingFiles
    value: "true"
  - name: extraArgs
    value:
      - "--metadata"
      - '{"application":"myapp","version":"2.0.0","environment":"production"}'
      - "--parallel-operations-count"
      - "15"
      - "--part-size"
      - "128"
      - "--cache-control"
      - "max-age=86400"
  workspaces:
  - name: credentials
    secret:
      secretName: oci-credentials
  - name: source
    emptyDir: {}
